[package]
name = "controller"
version = "0.1.0"
authors = ["Joeri Exelmans <joeri.exelmans@gmail.com>"]
edition = "2018"

[dependencies]
statechart = { path = "../statechart" }

[lib]
name = "controller"
path = "controller.rs"
