"""
Generated by Statechart compiler by Glenn De Jonghe, Joeri Exelmans, Simon Van Mierlo, and Yentl Van Tendeloo (for the inspiration)

Date:   Mon Aug 08 09:49:24 2016

Model author: Glenn De Jonghe
Model name:   TestGuard
Model description:
Testing the guard.
"""

from sccd.runtime.statecharts_core import *

# package "TestGuard"

class Class1(RuntimeClassBase):
    def __init__(self, controller):
        RuntimeClassBase.__init__(self, controller)
        
        self.semantics.big_step_maximality = StatechartSemantics.TakeMany
        self.semantics.internal_event_lifeline = StatechartSemantics.Queue
        self.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep
        self.semantics.priority = StatechartSemantics.SourceParent
        self.semantics.concurrency = StatechartSemantics.Single
        
        # build Statechart structure
        self.build_statechart_structure()
        
        # user defined attributes
        self.member1 = 0
        
        # call user defined constructor
        Class1.user_defined_constructor(self)
    
    def user_defined_constructor(self):
        pass
    
    def user_defined_destructor(self):
        pass
    
    
    # builds Statechart structure
    def build_statechart_structure(self):
        
        # state <root>
        self.states[""] = State(0, self)
        
        # state /state_1
        self.states["/state_1"] = State(1, self)
        self.states["/state_1"].setEnter(self._state_1_enter)
        
        # state /state_2
        self.states["/state_2"] = State(2, self)
        
        # state /state_3
        self.states["/state_3"] = State(3, self)
        self.states["/state_3"].setEnter(self._state_3_enter)
        
        # add children
        self.states[""].addChild(self.states["/state_1"])
        self.states[""].addChild(self.states["/state_2"])
        self.states[""].addChild(self.states["/state_3"])
        self.states[""].fixTree()
        self.states[""].default_state = self.states["/state_1"]
        
        # transition /state_1
        _state_1_0 = Transition(self, self.states["/state_1"], [self.states["/state_2"]])
        _state_1_0.setTrigger(None)
        self.states["/state_1"].addTransition(_state_1_0)
        
        # transition /state_2
        _state_2_0 = Transition(self, self.states["/state_2"], [self.states["/state_1"]])
        _state_2_0.setTrigger(None)
        _state_2_0.setGuard(self._state_2_0_guard)
        self.states["/state_2"].addTransition(_state_2_0)
        _state_2_1 = Transition(self, self.states["/state_2"], [self.states["/state_3"]])
        _state_2_1.setTrigger(None)
        _state_2_1.setGuard(self._state_2_1_guard)
        self.states["/state_2"].addTransition(_state_2_1)
    
    def _state_1_enter(self):
        self.member1 = self.member1 + 1
    
    def _state_3_enter(self):
        self.big_step.outputEvent(Event("received", "test_output", [self.member1]))
    
    def _state_2_0_guard(self, parameters):
        return self.member1 < 3
    
    def _state_2_1_guard(self, parameters):
        return self.member1 >= 3
    
    def initializeStatechart(self):
        # enter default state
        states = self.states["/state_1"].getEffectiveTargetStates()
        self.updateConfiguration(states)
        for state in states:
            if state.enter:
                state.enter()

class ObjectManager(ObjectManagerBase):
    def __init__(self, controller):
        ObjectManagerBase.__init__(self, controller)
    
    def instantiate(self, class_name, construct_params):
        if class_name == "Class1":
            instance = Class1(self.controller)
            instance.associations = {}
        else:
            raise Exception("Cannot instantiate class " + class_name)
        return instance

class Controller(ThreadsControllerBase):
    def __init__(self, keep_running = None):
        if keep_running == None: keep_running = True
        ThreadsControllerBase.__init__(self, ObjectManager(self), keep_running)
        self.addOutputPort("test_output")
        self.object_manager.createInstance("Class1", [])

class InputEvent:
    def __init__(self, name, port, parameters, time_offset):
        self.name = name
        self.port = port
        self.parameters = parameters
        self.time_offset = time_offset

class Test:
    def __init__(self):
        pass
    input_events = []
    expected_events = [[Event("received", "test_output", [3])]]