"""
Generated by Statechart compiler by Glenn De Jonghe, Joeri Exelmans, Simon Van Mierlo, and Yentl Van Tendeloo (for the inspiration)

Date:   Thu Aug 04 12:51:06 2016

Model author: Glenn De Jonghe
Model name:   TestMultipleTarget
Model description:
Testing the enter-exit sequence when having a transition that specificies a target state with multiple nodes.
"""

from sccd.runtime.statecharts_core import *

# package "TestMultipleTarget"

class Class1(RuntimeClassBase):
    def __init__(self, controller):
        RuntimeClassBase.__init__(self, controller)
        
        self.semantics.big_step_maximality = StatechartSemantics.TakeMany
        self.semantics.internal_event_lifeline = StatechartSemantics.Queue
        self.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep
        self.semantics.priority = StatechartSemantics.SourceParent
        self.semantics.concurrency = StatechartSemantics.Single
        
        # build Statechart structure
        self.build_statechart_structure()
        
        # call user defined constructor
        Class1.user_defined_constructor(self)
    
    def user_defined_constructor(self):
        pass
    
    def user_defined_destructor(self):
        pass
    
    
    # builds Statechart structure
    def build_statechart_structure(self):
        
        # state <root>
        self.states[""] = State(0, self)
        
        # state /parallel
        self.states["/parallel"] = ParallelState(1, self)
        
        # state /parallel/orthogonal_1
        self.states["/parallel/orthogonal_1"] = State(2, self)
        
        # state /parallel/orthogonal_1/inner_1
        self.states["/parallel/orthogonal_1/inner_1"] = State(3, self)
        self.states["/parallel/orthogonal_1/inner_1"].setEnter(self._parallel_orthogonal_1_inner_1_enter)
        
        # state /parallel/orthogonal_1/inner_2
        self.states["/parallel/orthogonal_1/inner_2"] = State(4, self)
        self.states["/parallel/orthogonal_1/inner_2"].setEnter(self._parallel_orthogonal_1_inner_2_enter)
        
        # state /parallel/orthogonal_2
        self.states["/parallel/orthogonal_2"] = State(5, self)
        
        # state /parallel/orthogonal_2/inner_1
        self.states["/parallel/orthogonal_2/inner_1"] = State(6, self)
        self.states["/parallel/orthogonal_2/inner_1"].setEnter(self._parallel_orthogonal_2_inner_1_enter)
        
        # state /parallel/orthogonal_2/inner_2
        self.states["/parallel/orthogonal_2/inner_2"] = State(7, self)
        self.states["/parallel/orthogonal_2/inner_2"].setEnter(self._parallel_orthogonal_2_inner_2_enter)
        
        # state /next_to_parallel
        self.states["/next_to_parallel"] = State(8, self)
        self.states["/next_to_parallel"].setEnter(self._next_to_parallel_enter)
        
        # add children
        self.states[""].addChild(self.states["/parallel"])
        self.states[""].addChild(self.states["/next_to_parallel"])
        self.states["/parallel"].addChild(self.states["/parallel/orthogonal_1"])
        self.states["/parallel"].addChild(self.states["/parallel/orthogonal_2"])
        self.states["/parallel/orthogonal_1"].addChild(self.states["/parallel/orthogonal_1/inner_1"])
        self.states["/parallel/orthogonal_1"].addChild(self.states["/parallel/orthogonal_1/inner_2"])
        self.states["/parallel/orthogonal_2"].addChild(self.states["/parallel/orthogonal_2/inner_1"])
        self.states["/parallel/orthogonal_2"].addChild(self.states["/parallel/orthogonal_2/inner_2"])
        self.states[""].fixTree()
        self.states[""].default_state = self.states["/next_to_parallel"]
        self.states["/parallel/orthogonal_1"].default_state = self.states["/parallel/orthogonal_1/inner_1"]
        self.states["/parallel/orthogonal_2"].default_state = self.states["/parallel/orthogonal_2/inner_1"]
        
        # transition /next_to_parallel
        _next_to_parallel_0 = Transition(self, self.states["/next_to_parallel"], [self.states["/parallel/orthogonal_1/inner_2"], self.states["/parallel/orthogonal_2/inner_2"]])
        self.states["/next_to_parallel"].addTransition(_next_to_parallel_0)
    
    def _parallel_orthogonal_1_inner_1_enter(self):
        self.big_step.outputEvent(Event("enter_1_1", "test_output", []))
    
    def _parallel_orthogonal_1_inner_2_enter(self):
        self.big_step.outputEvent(Event("enter_1_2", "test_output", []))
    
    def _parallel_orthogonal_2_inner_1_enter(self):
        self.big_step.outputEvent(Event("enter_2_1", "test_output", []))
    
    def _parallel_orthogonal_2_inner_2_enter(self):
        self.big_step.outputEvent(Event("enter_2_2", "test_output", []))
    
    def _next_to_parallel_enter(self):
        self.big_step.outputEvent(Event("enter_0", "test_output", []))
    
    def initializeStatechart(self):
        # enter default state
        states = self.states["/next_to_parallel"].getEffectiveTargetStates()
        self.updateConfiguration(states)
        for state in states:
            if state.enter:
                state.enter()

class ObjectManager(ObjectManagerBase):
    def __init__(self, controller):
        ObjectManagerBase.__init__(self, controller)
    
    def instantiate(self, class_name, construct_params):
        if class_name == "Class1":
            instance = Class1(self.controller)
            instance.associations = {}
        else:
            raise Exception("Cannot instantiate class " + class_name)
        return instance

class Controller(ThreadsControllerBase):
    def __init__(self, keep_running = None):
        if keep_running == None: keep_running = True
        ThreadsControllerBase.__init__(self, ObjectManager(self), keep_running)
        self.addInputPort("test_input")
        self.addOutputPort("test_output")
        self.object_manager.createInstance("Class1", [])

class InputEvent:
    def __init__(self, name, port, parameters, time_offset):
        self.name = name
        self.port = port
        self.parameters = parameters
        self.time_offset = time_offset

class Test:
    def __init__(self):
        pass
    input_events = []
    expected_events = [[Event("enter_0", "test_output", [])], [Event("enter_1_2", "test_output", []), Event("enter_2_2", "test_output", [])]]