/* Generated by Statechart compiler by Glenn De Jonghe, Joeri Exelmans, Simon Van Mierlo, and Yentl Van Tendeloo (for the inspiration)

Date:   Tue Aug 09 09:35:53 2016

Model author: Glenn De Jonghe
Model name:   TestParallel
Model description:
Testing parallelism.*/


// package "TestParallel"
var TestParallel = {};
(function() {

var Class1 = function(controller) {
    RuntimeClassBase.call(this, controller);
    
    this.semantics.big_step_maximality = StatechartSemantics.TakeMany;
    this.semantics.internal_event_lifeline = StatechartSemantics.Queue;
    this.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep;
    this.semantics.priority = StatechartSemantics.SourceParent;
    this.semantics.concurrency = StatechartSemantics.Single;
    
    // build Statechart structure
    this.build_statechart_structure();
    
    // call user defined constructor
    Class1.prototype.user_defined_constructor.call(this);
};
Class1.prototype = new Object();
(function() {
    var proto = new RuntimeClassBase();
    for (prop in proto) {
        Class1.prototype[prop] = proto[prop];
    }
})();

Class1.prototype.user_defined_constructor = function() {
};

Class1.prototype.user_defined_destructor = function() {
};


// builds Statechart structure
Class1.prototype.build_statechart_structure = function() {
    
    // state <root>
    this.states[""] = new State(0, this);
    
    // state /parallel_1
    this.states["/parallel_1"] = new ParallelState(1, this);
    
    // state /parallel_1/orthogonal_1
    this.states["/parallel_1/orthogonal_1"] = new State(2, this);
    
    // state /parallel_1/orthogonal_1/state_1
    this.states["/parallel_1/orthogonal_1/state_1"] = new State(3, this);
    this.states["/parallel_1/orthogonal_1/state_1"].setEnter(this._parallel_1_orthogonal_1_state_1_enter);
    
    // state /parallel_1/orthogonal_1/state_2
    this.states["/parallel_1/orthogonal_1/state_2"] = new State(4, this);
    this.states["/parallel_1/orthogonal_1/state_2"].setEnter(this._parallel_1_orthogonal_1_state_2_enter);
    
    // state /parallel_1/orthogonal_2
    this.states["/parallel_1/orthogonal_2"] = new State(5, this);
    
    // state /parallel_1/orthogonal_2/state_3
    this.states["/parallel_1/orthogonal_2/state_3"] = new State(6, this);
    this.states["/parallel_1/orthogonal_2/state_3"].setEnter(this._parallel_1_orthogonal_2_state_3_enter);
    
    // state /parallel_1/orthogonal_2/state_4
    this.states["/parallel_1/orthogonal_2/state_4"] = new State(7, this);
    this.states["/parallel_1/orthogonal_2/state_4"].setEnter(this._parallel_1_orthogonal_2_state_4_enter);
    
    // add children
    this.states[""].addChild(this.states["/parallel_1"]);
    this.states["/parallel_1"].addChild(this.states["/parallel_1/orthogonal_1"]);
    this.states["/parallel_1"].addChild(this.states["/parallel_1/orthogonal_2"]);
    this.states["/parallel_1/orthogonal_1"].addChild(this.states["/parallel_1/orthogonal_1/state_1"]);
    this.states["/parallel_1/orthogonal_1"].addChild(this.states["/parallel_1/orthogonal_1/state_2"]);
    this.states["/parallel_1/orthogonal_2"].addChild(this.states["/parallel_1/orthogonal_2/state_3"]);
    this.states["/parallel_1/orthogonal_2"].addChild(this.states["/parallel_1/orthogonal_2/state_4"]);
    this.states[""].fixTree();
    this.states[""].default_state = this.states["/parallel_1"];
    this.states["/parallel_1/orthogonal_1"].default_state = this.states["/parallel_1/orthogonal_1/state_1"];
    this.states["/parallel_1/orthogonal_2"].default_state = this.states["/parallel_1/orthogonal_2/state_3"];
    
    // transition /parallel_1/orthogonal_1/state_1
    var _parallel_1_orthogonal_1_state_1_0 = new Transition(this, this.states["/parallel_1/orthogonal_1/state_1"], [this.states["/parallel_1/orthogonal_1/state_2"]]);
    _parallel_1_orthogonal_1_state_1_0.setTrigger(new Event("to_state_2", "test_input"));
    this.states["/parallel_1/orthogonal_1/state_1"].addTransition(_parallel_1_orthogonal_1_state_1_0);
    
    // transition /parallel_1/orthogonal_1/state_2
    var _parallel_1_orthogonal_1_state_2_0 = new Transition(this, this.states["/parallel_1/orthogonal_1/state_2"], [this.states["/parallel_1/orthogonal_1/state_1"]]);
    _parallel_1_orthogonal_1_state_2_0.setTrigger(new Event("to_state_1", "test_input"));
    this.states["/parallel_1/orthogonal_1/state_2"].addTransition(_parallel_1_orthogonal_1_state_2_0);
    
    // transition /parallel_1/orthogonal_2/state_3
    var _parallel_1_orthogonal_2_state_3_0 = new Transition(this, this.states["/parallel_1/orthogonal_2/state_3"], [this.states["/parallel_1/orthogonal_2/state_4"]]);
    _parallel_1_orthogonal_2_state_3_0.setTrigger(new Event("to_state_4", "test_input"));
    this.states["/parallel_1/orthogonal_2/state_3"].addTransition(_parallel_1_orthogonal_2_state_3_0);
    
    // transition /parallel_1/orthogonal_2/state_4
    var _parallel_1_orthogonal_2_state_4_0 = new Transition(this, this.states["/parallel_1/orthogonal_2/state_4"], [this.states["/parallel_1/orthogonal_2/state_3"]]);
    _parallel_1_orthogonal_2_state_4_0.setTrigger(new Event("to_state_3", "test_input"));
    this.states["/parallel_1/orthogonal_2/state_4"].addTransition(_parallel_1_orthogonal_2_state_4_0);
};

Class1.prototype._parallel_1_orthogonal_1_state_1_enter = function() {
    this.big_step.outputEvent(new Event("in_state_1", "test_output", new Array()));
};

Class1.prototype._parallel_1_orthogonal_1_state_2_enter = function() {
    this.big_step.outputEvent(new Event("in_state_2", "test_output", new Array()));
};

Class1.prototype._parallel_1_orthogonal_2_state_3_enter = function() {
    this.big_step.outputEvent(new Event("in_state_3", "test_output", new Array()));
};

Class1.prototype._parallel_1_orthogonal_2_state_4_enter = function() {
    this.big_step.outputEvent(new Event("in_state_4", "test_output", new Array()));
};

Class1.prototype.initializeStatechart = function() {
    // enter default state
    this.default_targets = this.states["/parallel_1"].getEffectiveTargetStates();
    RuntimeClassBase.prototype.initializeStatechart.call(this);
};

// add symbol 'Class1' to package 'TestParallel'
TestParallel.Class1 = Class1;

var ObjectManager = function(controller) {
    ObjectManagerBase.call(this, controller);
};
ObjectManager.prototype = new Object();
(function() {
    var proto = new ObjectManagerBase();
    for (prop in proto) {
        ObjectManager.prototype[prop] = proto[prop];
    }
})();

ObjectManager.prototype.instantiate = function(class_name, construct_params) {
    if (class_name === "Class1") {
        var instance = new Class1(this.controller);
        instance.associations = new Object();
    } else  {
        throw new Error("Cannot instantiate class " + class_name);
    }
    return instance;
};

// add symbol 'ObjectManager' to package 'TestParallel'
TestParallel.ObjectManager = ObjectManager;

var Controller = function(event_loop_callbacks, finished_callback, behind_schedule_callback) {
    if (finished_callback === undefined) finished_callback = null;
    if (behind_schedule_callback === undefined) behind_schedule_callback = null;
    EventLoopControllerBase.call(this, new ObjectManager(this), event_loop_callbacks, finished_callback, behind_schedule_callback);
    this.addInputPort("test_input");
    this.addOutputPort("test_output");
    this.object_manager.createInstance("Class1", new Array());
};
Controller.prototype = new Object();
(function() {
    var proto = new EventLoopControllerBase();
    for (prop in proto) {
        Controller.prototype[prop] = proto[prop];
    }
})();

// add symbol 'Controller' to package 'TestParallel'
TestParallel.Controller = Controller;

var InputEvent = function(name, port, parameters, time_offset) {
    this.name = name;
    this.port = port;
    this.parameters = parameters;
    this.time_offset = time_offset;
};

// add symbol 'InputEvent' to package 'TestParallel'
TestParallel.InputEvent = InputEvent;

var Test = function() {
};
Test.prototype.input_events = [new InputEvent("to_state_2", "test_input", new Array(), 0.0), new InputEvent("to_state_4", "test_input", new Array(), 0.0), new InputEvent("to_state_1", "test_input", new Array(), 0.0), new InputEvent("to_state_2", "test_input", new Array(), 0.0), new InputEvent("to_state_3", "test_input", new Array(), 0.0)];
Test.prototype.expected_events = [[new Event("in_state_1", "test_output", new Array()), new Event("in_state_3", "test_output", new Array())], [new Event("in_state_2", "test_output", new Array())], [new Event("in_state_4", "test_output", new Array())], [new Event("in_state_1", "test_output", new Array())], [new Event("in_state_2", "test_output", new Array())], [new Event("in_state_3", "test_output", new Array())]];

// add symbol 'Test' to package 'TestParallel'
TestParallel.Test = Test;
})();